### ISSUE TITLE
Create a sticker variant with "bleed"

### ISSUE THREAD

**Issue by garrett** [garrett/Tux#10] opened 2020-05-15 16:18 UTC
StickerMule needs a version of Tux that's optimized for sticker usage. This requires color bleed off the edges so when the Tux sticker is cut, the color will bump right up to the edges.

Quoting @ifohancroft from https://github.com/garrett/Tux/pull/8#issuecomment-621994491:
> To be able to print designs in full bleed, their outer edges need to have 1/8th inch of flat color.

Example:
![W3UR5EP](https://user-images.githubusercontent.com/10246/82072553-308ef900-96d8-11ea-8a22-bcb5a5d78311.png)

And from https://github.com/garrett/Tux/pull/8#issuecomment-624190623, here's an example PDF of what's needed too: [tux-full-bleed.pdf](https://github.com/garrett/Tux/files/4635611/tux-full-bleed.pdf)

**Comment by ifohancroft** [comment] 2020-05-15 16:24
The rest doesn't need to be changed according to the PDF. It's just the part of the feet that's marked in red, however since the PDF has been generated and sent by them, I felt it may better represent the depth of the feet part that I've marked in red that needs to be solid color.

**Comment by garrett** [comment] 2020-05-16 18:57
Here's what I have so far — do you think something like this would work?

I've done a few tricks to extend Tux past the cut line:
![tux-sticker](https://user-images.githubusercontent.com/10246/82127970-91d9c980-97b7-11ea-9677-48e7ea7940b9.png)

And here's the same thing with the cut line so you can see the content inside and what extends past:
![tux-sticker-bleed-preview](https://user-images.githubusercontent.com/10246/82127972-969e7d80-97b7-11ea-8aeb-95aef588024c.png)

Do you know precisely what size these should be printed at? I guess they could scale it too, but it might be nice to format the document to-size. (We could do that later too, I guess.)

If this is good, I can toss a PR on this repo with SVG and PNG exports.

**Comment by ifohancroft** [comment] 2020-05-16 21:15
Sorry. Perhaps I haven't explained well.
Check my previous comment on here.

**Comment by garrett** [comment] 2020-05-18 15:43
> The only thing that needs to be done is a small part of the feet shadows (around the outside edges of the feet (what I have makred in red)) needs to be made flat.

Could we just drop the shadows?

Or do you mean it should be a solid color (without gradients at all) on the edge?

**Comment by ifohancroft** [comment] 2020-05-18 18:13
> > The only thing that needs to be done is a small part of the feet shadows (around the outside edges of the feet (what I have makred in red)) needs to be made flat.
> 
> Could we just get rid of the shadows in the SVG?
> 
> Or do you mean it should be a solid color (without gradients at all) on the edge?
> 
> Often "flat" means to not have alpha. Is that what is meant? Or something else?

Sorry, yeah, I should have been clearer. The edge should be a solid color, without gradients at all.

**Comment by ifohancroft** [comment] 2020-05-21 00:11
By the way, just letting you know that I will be away for a week, so I will be away from a computer for the most part. Also, just reminding you to update https://en.wikipedia.org/wiki/Tux_(mascot)#/media/File:Tux.svg with the new version (I presume you have uploaded this one?)

**Comment by garrett** [comment] 2020-05-25 12:58
> The edge should be a solid color, without gradients at all.

That's rather difficult, as there isn't really a single solid color that's shared with the either foot. The top would either be too dark or the bottom would be too light.

I guess we could stroke it with the darker color so the top looks shaded — it would be better than the opposite direction. After all, cartoon characters often have dark outlines anyway?

**Comment by ifohancroft** [comment] 2020-05-25 14:38
I was thinking something like that too.
Since the color is still going to sit on the feet themselves, not outside of them and only on the insidd of the feet's outer edge, where they are not facing the body but the empty outside, the darker color of the shadow that usually sits there can be taken and made flat. Not the darkest shade but something that's close to neighbouring yellow/orange. Also, it doesn't have to be the same color on both feet.

**Comment by ifohancroft** [comment] 2020-05-28 22:49
I am back at home.

Btw here is an image showing exactly which parts of the feet need to be flat color. Hopefully, this one better illustrates exactly what I mean by Inside of the feet outline but their outer parts that are not touching the body.

![tux-for-sticker](https://user-images.githubusercontent.com/3461282/83201660-a9696880-a14e-11ea-9a6b-2493f3f879e7.png)

**Comment by ifohancroft** [comment] 2020-06-08 18:18
Hey! Just checking to see if you've had a chance to read my previous two comments on this issue.

**Comment by garrett** [comment] 2020-06-17 17:14
I'm sorry it took me way to long to get back to you on this. :cry:

Anyway, I think this might be what you're looking for?
![tux-sticker-preview](https://user-images.githubusercontent.com/10246/84928310-7a4f7280-b0ce-11ea-9adc-7d08969db8ac.png)

SVG is in the branch @ https://github.com/garrett/Tux/blob/sticker/sticker/tux-sticker.svg

I split the difference between the colors and basically lightened up the orange at the edges in the process. I also lightened the beak a little to match.

**Comment by ifohancroft** [comment] 2020-06-17 17:21
No problem at all! Life happens...
I think this should be perfect. I'll contact Sticker Mule about it in a bit, to make sure.
I think we should still keep the regular one, like we talked and have this one as the sticker version, but I must say: This one also looks very beautiful! You've done a great job with it! Thank you!

P.S. I think I forgot to tell you: I've updatsd the SVG that's on Wikipedia so it now contains the latest version.

**Comment by garrett** [comment] 2020-06-18 13:07
>  I think this should be perfect. I'll contact Sticker Mule about it in a bit, to make sure.

Cool! Once they confirm, we can merge in the sticker branch. (Perhaps with a README to explain things, like that it's what is fine by StickerMule and other vendors may vary.)

> P.S. I think I forgot to tell you: I've updatsd the SVG that's on Wikipedia so it now contains the latest version.

Excellent! Thanks!

**Comment by ifohancroft** [comment] 2020-06-24 20:49
It is printable full bleed (without border now) and pretty much everything seems to be ok. Just in case, I've made a test order. When they arrive I'll let you know and if everything's ok, we can add it to the repo.

**Comment by ifohancroft** [comment] 2020-07-17 11:18
I have received the stickers and they did not come out as they should. I will work with Sticker Mule to figure out the problem and let you know if we need to make a change or not, then I'll order new stickers when I can, confirm they are ok and so on.

**Comment by garrett** [comment] 2020-07-17 15:52
Oh drat. I hope you/they can figure out what happened.

Thanks for the update! Hopefully we'll get something that works well soon.

**Comment by ifohancroft** [comment] 2020-09-03 20:31
I am sorry it has taken me so long to get back to you. The issue has been identified, a fix has been suggested and the problem is not with the design. I'd like to test the suggested fix (do one or two more order, submitting the files that they have suggested and after I receive them and confirm that there are no problems, I'll push to the repo and explain in detail).

Before testing the hopefully final test order however, I have noticed a tiny detail in the sticker design that I think would better if changed. I'll write a bit later and show an example of what I mean.

**Comment by ifohancroft** [comment] 2021-02-16 02:58
Sorry. I am back now and ready to go ahead full speed so we can finish it and have our favorite mascot ready for everyone!
I have just sent a Sticker Mule order (sorry, couldn't afford it earlier) to confirm their suggested fix works. P.S. Check your Twitter PMs.

**Comment by ifohancroft** [comment] 2021-03-31 15:19
Now we can close this issue/ticket.

**Closed** 2021-05-08 13:10 UTC
